// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/healthz": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/metaobjects": {
    params: {};
  };
  "/app/references": {
    params: {};
  };
  "/app/discovery": {
    params: {};
  };
  "/app/products": {
    params: {};
  };
  "/app/products/:productId": {
    params: {
      "productId": string;
    };
  };
  "/app/files": {
    params: {};
  };
  "/app/bulk": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/login" | "/healthz" | "/auth/*" | "/app" | "/app/metaobjects" | "/app/references" | "/app/discovery" | "/app/products" | "/app/products/:productId" | "/app/files" | "/app/bulk";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/healthz.ts": {
    id: "routes/healthz";
    page: "/healthz";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/metaobjects" | "/app/references" | "/app/discovery" | "/app/products" | "/app/products/:productId" | "/app/files" | "/app/bulk";
  };
  "routes/app.metaobjects.tsx": {
    id: "routes/app.metaobjects";
    page: "/app/metaobjects";
  };
  "routes/app.references.tsx": {
    id: "routes/app.references";
    page: "/app/references";
  };
  "routes/app.discovery.tsx": {
    id: "routes/app.discovery";
    page: "/app/discovery";
  };
  "routes/app.products.tsx": {
    id: "routes/app.products";
    page: "/app/products" | "/app/products/:productId";
  };
  "routes/app.products.$productId.tsx": {
    id: "routes/app.products.$productId";
    page: "/app/products/:productId";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.files.tsx": {
    id: "routes/app.files";
    page: "/app/files";
  };
  "routes/app.bulk.tsx": {
    id: "routes/app.bulk";
    page: "/app/bulk";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/healthz": typeof import("./app/routes/healthz.ts");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.metaobjects": typeof import("./app/routes/app.metaobjects.tsx");
  "routes/app.references": typeof import("./app/routes/app.references.tsx");
  "routes/app.discovery": typeof import("./app/routes/app.discovery.tsx");
  "routes/app.products": typeof import("./app/routes/app.products.tsx");
  "routes/app.products.$productId": typeof import("./app/routes/app.products.$productId.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.files": typeof import("./app/routes/app.files.tsx");
  "routes/app.bulk": typeof import("./app/routes/app.bulk.tsx");
};