# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c2a6206c234b70e154aa29581063729"
name = "Migration (receive)"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_price_rules,write_price_rules,read_discounts,write_discounts,read_discounts_allocator_functions,write_discounts_allocator_functions,read_files,write_files,write_inventory,read_inventory,read_locales,write_locales,read_locations,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_online_store_navigation,write_online_store_navigation,read_products,write_products,read_publications,write_publications,read_content,write_content,read_orders,read_all_orders,read_customers,write_customers,read_themes,write_themes,read_translations,write_translations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/auth/callback",
]
